# Titanic - Machine Learning from Disaster

https://www.kaggle.com/c/titanic

In [4]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix, accuracy_score


In [5]:
titanic_path = '/home/ubuntu/pCloudDrive/18.Kaggle microcourses/00.Kaggle micro-courses/07.Intro to Machine Learning/02.Kaggle Playground Competition: Titanic/titanic/'
train_data = pd.read_csv(titanic_path + 'train.csv')
test_data = pd.read_csv(titanic_path + 'test.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/pCloudDrive/18.Kaggle microcourses/00.Kaggle micro-courses/07.Intro to Machine Learning/02.Kaggle aPlayground Competition: Titanic/titanic/train.csv'

In [3]:
train_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
#Choose y and X before doing processing firstly, because there is no point carrying data not used in memory and secondly because imputation wont work on strings
y = train_data['Survived']
X = train_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]

In [5]:
def encodeSex(df):
    label_encoder = LabelEncoder()
    df['Sex'] = label_encoder.fit_transform(df['Sex'])
    return df

In [6]:
encodeSex(X)

<ipython-input-5-9512c64f3f47>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = label_encoder.fit_transform(df['Sex'])


Pclass  Sex   Age  SibSp  Parch     Fare
0         3    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         3    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         3    1  35.0      0      0   8.0500
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0  13.0000
887       1    0  19.0      0      0  30.0000
888       3    0   NaN      1      2  23.4500
889       1    1  26.0      0      0  30.0000
890       3    1  32.0      0      0   7.7500

[891 rows x 6 columns]

In [7]:
def numpymissingAge(df):
    df['Age'] = df['Age'].fillna(method = 'bfill', axis = 0).fillna(0)
    return df

In [8]:
numpymissingAge(X)

<ipython-input-7-b46c20b9b309>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(method = 'bfill', axis = 0).fillna(0)


Pclass  Sex   Age  SibSp  Parch     Fare
0         3    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         3    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         3    1  35.0      0      0   8.0500
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0  13.0000
887       1    0  19.0      0      0  30.0000
888       3    0  26.0      1      2  23.4500
889       1    1  26.0      0      0  30.0000
890       3    1  32.0      0      0   7.7500

[891 rows x 6 columns]

In [12]:
'''
def imputationmissingAge(df):
    my_imputer = SimpleImputer()
    df = pd.DataFrame(my_imputer.fit_transform(df))
    df.columns = df.columns
    return df
    
'''

'\ndef imputationmissingAge(df):\n    my_imputer = SimpleImputer()\n    df = pd.DataFrame(my_imputer.fit_transform(df))\n    df.columns = df.columns\n    return df\n    \n'

In [13]:
'''imputationmissingAge(X)'''

'imputationmissingAge(X)'

In [14]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

### Train test split of cleaned training data before algo implementation

In [9]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 1)

### Running several algorithms to decide which to use for test data

In [10]:
def logisticRegression(train_X, val_X, train_y, val_y):
    
    logreg = LogisticRegression()
    logreg.fit(train_X, train_y)

    val_predictions = logreg.predict(val_X)

    print(confusion_matrix(val_y, val_predictions))
    print(accuracy_score(val_y, val_predictions))

In [11]:
logisticRegression(train_X, val_X, train_y, val_y)

[[114  14]
 [ 29  66]]
0.8071748878923767


In [13]:
def KNN(train_X, val_X, train_y, val_y):
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(train_X, train_y)
    
    val_predictions = classifier.predict(val_X)

    print(confusion_matrix(val_y, val_predictions))
    print(accuracy_score(val_y, val_predictions))

In [14]:
KNN(train_X, val_X, train_y, val_y)

[[107  21]
 [ 50  45]]
0.6816143497757847


In [15]:
def supportvectors(train_X, val_X, train_y, val_y):
    classifier = SVC(kernel = 'linear')
    classifier.fit(train_X, train_y)
    
    val_predictions = classifier.predict(val_X)

    print(confusion_matrix(val_y, val_predictions))
    print(accuracy_score(val_y, val_predictions))

In [16]:
supportvectors(train_X, val_X, train_y, val_y)

[[111  17]
 [ 31  64]]
0.7847533632286996


In [17]:
def naivebayes(train_X, val_X, train_y, val_y):
    classifier = GaussianNB()
    classifier.fit(train_X, train_y)
    
    val_predictions = classifier.predict(val_X)
    
    print(confusion_matrix(val_y, val_predictions))
    print(accuracy_score(val_y, val_predictions))

In [18]:
naivebayes(train_X, val_X, train_y, val_y)

[[109  19]
 [ 34  61]]
0.7623318385650224


In [12]:
def decisionTree(train_X, val_X, train_y, val_y):
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(train_X, train_y)
    
    val_predictions = classifier.predict(val_X)
    
    print(confusion_matrix(val_y, val_predictions))
    print(accuracy_score(val_y, val_predictions))

In [13]:
decisionTree(train_X, val_X, train_y, val_y)

[[107  21]
 [ 34  61]]
0.7533632286995515


In [14]:
def randomForest(train_X, val_X, train_y, val_y):
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(train_X, train_y)
    
    val_predictions = classifier.predict(val_X)
    
    print(confusion_matrix(val_y, val_predictions))
    print(accuracy_score(val_y, val_predictions))

In [15]:
randomForest(train_X, val_X, train_y, val_y)

[[116  12]
 [ 41  54]]
0.7623318385650224


### Predicting on test data and generating submission file

In [105]:
X_test = test_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]

In [107]:
encodeSex(X_test)

<ipython-input-5-5ffb710b24f7>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = label_encoder.fit_transform(df['Sex'])


0      1
1      0
2      1
3      1
4      0
      ..
413    1
414    0
415    1
416    1
417    1
Name: Sex, Length: 418, dtype: int64

In [117]:
numpymissingAge(X_test)

<ipython-input-20-b46c20b9b309>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(method = 'bfill', axis = 0).fillna(0)


Pclass  Sex   Age  SibSp  Parch      Fare
0         3    1  34.5      0      0    7.8292
1         3    0  47.0      1      0    7.0000
2         2    1  62.0      0      0    9.6875
3         3    1  27.0      0      0    8.6625
4         3    0  22.0      1      1   12.2875
..      ...  ...   ...    ...    ...       ...
413       3    1  39.0      0      0    8.0500
414       1    0  39.0      0      0  108.9000
415       3    1  38.5      0      0    7.2500
416       3    1   0.0      0      0    8.0500
417       3    1   0.0      1      1   22.3583

[418 rows x 6 columns]

In [112]:
X_test.iloc[:,5] = X_test.iloc[:,5].fillna(method = 'bfill', axis = 0).fillna(0)

/home/ubuntu/snap/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


In [119]:
val_predictions1 = logreg.predict(X_test)


In [124]:
val_predictions1.size

418